"""email changed to username on account table

Revision ID: 1f97f36ca14c
Revises: 7a9556ef6dc8
Create Date: 2025-11-18 22:55:39.166537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1f97f36ca14c'
down_revision: Union[str, Sequence[str], None] = '7a9556ef6dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint(op.f('accounts_email_key'), 'accounts', type_='unique')
    op.create_unique_constraint(None, 'accounts', ['username'])
    op.drop_column('accounts', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'accounts', type_='unique')
    op.create_unique_constraint(op.f('accounts_email_key'), 'accounts', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('accounts', 'username')
    # ### end Alembic commands ###
