"""store item ondelete updated

Revision ID: 2abef8f08cf6
Revises: 93dd2cee3d41
Create Date: 2025-11-20 10:18:31.210169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2abef8f08cf6'
down_revision: Union[str, Sequence[str], None] = '93dd2cee3d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('store_items_item_id_fkey'), 'store_items', type_='foreignkey')
    op.drop_constraint(op.f('store_items_store_id_fkey'), 'store_items', type_='foreignkey')
    op.create_foreign_key(None, 'store_items', 'stores', ['store_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'store_items', 'items', ['item_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_items', type_='foreignkey')
    op.drop_constraint(None, 'store_items', type_='foreignkey')
    op.create_foreign_key(op.f('store_items_store_id_fkey'), 'store_items', 'stores', ['store_id'], ['id'])
    op.create_foreign_key(op.f('store_items_item_id_fkey'), 'store_items', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
