"""tax and item table added

Revision ID: 7a9556ef6dc8
Revises: 8f9046c68d44
Create Date: 2025-11-18 14:58:40.468730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7a9556ef6dc8'
down_revision: Union[str, Sequence[str], None] = '8f9046c68d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxes',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('percent', sa.Integer(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('percent')
                    )
    op.create_table('items',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('code', sa.String(), nullable=True),
                    sa.Column('category_id', sa.UUID(), nullable=False),
                    sa.Column('color_id', sa.UUID(), nullable=True),
                    sa.Column('size_id', sa.UUID(), nullable=True),
                    sa.Column('currency_id', sa.UUID(), nullable=False),
                    sa.Column('unit_id', sa.UUID(), nullable=False),
                    sa.Column('tax_id', sa.UUID(), nullable=False),
                    sa.Column('unit_cost', sa.Double(), nullable=False),
                    sa.Column('selling_price', sa.Double(), nullable=False),
                    sa.Column('min_selling_price', sa.Double(), nullable=False),
                    sa.Column('warning_quantity', sa.Integer(), nullable=False),
                    sa.Column('is_publicly_visible', sa.Boolean(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('images', sa.ARRAY(sa.String()), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
                    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
                    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
                    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], ),
                    sa.ForeignKeyConstraint(['tax_id'], ['taxes.id'], ),
                    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('taxes')
    # ### end Alembic commands ###
