"""store item table added

Revision ID: 93dd2cee3d41
Revises: 919bae872a7e
Create Date: 2025-11-20 10:13:50.946885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '93dd2cee3d41'
down_revision: Union[str, Sequence[str], None] = '919bae872a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_items',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('item_id', sa.UUID(), nullable=False),
                    sa.Column('store_id', sa.UUID(), nullable=False),
                    sa.Column('quantity', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
                    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('item_id', 'store_id', name='uni_store_item')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_items')
    # ### end Alembic commands ###
