"""item model updated

Revision ID: d5e979cd5f0f
Revises: 2abef8f08cf6
Create Date: 2025-12-01 15:07:55.517185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e979cd5f0f'
down_revision: Union[str, Sequence[str], None] = '2abef8f08cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'unit_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('items', 'tax_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'tax_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('items', 'unit_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
